@WMS.API_HostAddress=https://localhost:7248
@AdminId=0b73f30c-c19a-4a81-a9b7-8413963512e6

//Get of Warehouse
# GET {{WMS.API_HostAddress}}/weatherforecast/
# Accept:application/json


//POST of Warehouse
POST {{WMS.API_HostAddress}}/api/Warehouse
Content-Type: application/json

{
  "WarehouseType": "Small",
  "WarehouseName": "sub AusterWarehouse",
  "adminId": "{{AdminId}}"
}

# {
#    "Id":"{{AdminId}}",
#    "WarehouseName":""
# }